service: generate-pdf
frameworkVersion: '2'

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: eu-central-1
  stage: prod
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 's3:PutObject'
        - 's3:PutObjectAcl'
      Resource: 'arn:aws:s3:::my-bucket-name/*'

custom:
  webpack:
    includeModules: true # Node modules configuration for packaging

functions:
  configurator-pdf:
    handler: handler.pdf
    events:
      - httpApi: '*'
