service: generate-pdf
frameworkVersion: '2'

plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: eu-central-1
  stage: ${opt:stage, 'production'}
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 's3:PutObject'
        - 's3:PutObjectAcl'
      Resource: 'arn:aws:s3:::my-bucket-name/*'
  environment:
    NODE_ENV: ${self:provider.stage}

custom:
  webpack:
    includeModules: true # Node modules configuration for packaging

functions:
  generate-pdf:
    handler: handler.pdf
    description: Generate a PDF based on a React template injecting input data, upload it on S3 and return the URL
    events:
      - httpApi:
          method: POST
          path: /
